#!/bin/bash

# Sleep to allow Elasticsearch to finish initializing
# if it's not done doing whatever it does yet
echo "Waiting for Elasticsearch"

until wget -qO - $ELASTICSEARCH_HOST; do
  echo "."
  sleep 2
done

echo -n "Waiting for Postgres"

while ! nc -z $POSTGRES_HOST $POSTGRES_PORT; do
  echo "."
  sleep 2
done

echo ""

if [[ $MIX_ENV == "dev" ]]; then
  /bin/run-development
  exit $?
fi

#mix ecto.load -r Philomena.Repo -d priv/repo/structure.sql --skip-if-loaded
#mix ecto.migrate -r Philomena.Repo

# Get local IP
PHILO_POD_IP=$(ip route get 1.1.1.1 | head -1 | cut -d' ' -f7)

echo "Starting Philomena with IP $PHILO_POD_IP"

/srv/philomena/_build/prod/rel/philomena/bin/philomena start