tabWidth: 2
useTabs: false
printWidth: 120
semi: true
singleQuote: true
bracketSpacing: true
endOfLine: lf
quoteProps: as-needed
trailingComma: all
arrowParens: avoid
overrides:
  - files: "*.css"
    options:
      singleQuote: false
