FROM node:lts

COPY ./assets /srv/philomena/assets
COPY ./priv /srv/philomena/priv
WORKDIR /srv/
RUN addgroup philomena && \
  adduser --home /srv/ --system --shell /bin/nologin --uid 200 --ingroup philomena philomena
RUN chown -R philomena:philomena /srv/
USER 200
WORKDIR /srv/philomena/assets
RUN npm install
RUN npm run deploy

FROM nginx:1.18.0-alpine-perl

ENV APP_HOST=app.derpibooru-legacy.svc.cluster.local

COPY docker/web/site.conf /etc/nginx/conf.d/default.conf
COPY docker/web/nginx.conf /etc/nginx/nginx.conf
COPY --from=0 /srv/philomena/priv/static /srv/assets/static
EXPOSE 8080
RUN chown -R 200:200 /tmp
USER 200
CMD nginx -g 'daemon off;'
