#!/bin/sh
set -e

export RELEASE_NODE=philomena_runner_0

philomena eval 'Philomena.Release.update_channels()'
philomena eval 'Philomena.Release.verify_artist_links()'
philomena eval 'Philomena.Release.update_stats()'
