import Config

# Configure your database
config :philomena, Philomena.Repo,
  username: "postgres",
  password: "postgres",
  database: "philomena_db",
  hostname: "postgres",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :philomena,
  elasticsearch_url: "http://elasticsearch:9200",
  redis_host: "redis"

config :exq,
  host: "redis"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :philomena, PhilomenaWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    npm: ["run", "watch", cd: Path.expand("../assets", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :philomena, PhilomenaWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/philomena_web/{live,views}/.*(ex)$",
      ~r"lib/philomena_web/templates/.*(eex|slim|slime)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"
config :logger, compile_time_purge_matching: [[application: :remote_ip], [application: :mint]]

# Set up mailer
config :philomena, PhilomenaWeb.Mailer, adapter: Bamboo.LocalAdapter

config :philomena, :mailer_address, "noreply@philomena.lc"

# Use this to debug slime templates
# config :slime, :keep_lines, true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
