---
extends: stylelint-config-recommended
rules:
  block-no-empty: true
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - mixin
        - define-mixin
  media-query-no-invalid:
  rule-empty-line-before:
    - always-multi-line
    - except:
        - after-single-line-comment
        - first-nested
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties: true
  font-family-no-duplicate-names: true
  keyframe-block-no-duplicate-selectors: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: null
  color-no-invalid-hex: true
  function-calc-no-unspaced-operator: true
  named-grid-areas-no-invalid: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: true
  string-no-newline: true
  no-irregular-whitespace: true
  custom-property-no-missing-var-function: true
  font-family-no-missing-generic-family-keyword: true
  function-linear-gradient-no-nonstandard-direction: true
  declaration-block-no-shorthand-property-overrides: true
  selector-anb-no-unmatchable: true
  function-no-unknown: true
  media-feature-name-no-unknown: true
  media-feature-name-value-no-unknown: true
  no-unknown-animations: true
  length-zero-no-unit: true
  media-feature-name-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true
  function-name-case: lower
  selector-type-case: lower
  value-keyword-case: lower
  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - blockless-after-blockless
  custom-property-empty-line-before: never
  declaration-empty-line-before: never
  declaration-block-single-line-max-declarations: 3
  number-max-precision: 2
  max-nesting-depth: 1
  color-hex-length: long
  alpha-value-notation: number
  font-weight-notation: named-where-possible
  hue-degree-notation: number
  import-notation: string
  keyframe-selector-notation: percentage-unless-within-keyword-only-block
  lightness-notation: percentage
  media-feature-range-notation: prefix
  selector-not-notation: simple
  selector-pseudo-element-colon-notation: single
  custom-property-pattern: "[a-z\\-\\$]+"
  selector-class-pattern: "^[a-z\\-_]+(\\-\\-|__)?[a-z\\-]*(\\-\\-|__)?[0-9a-z\\-]*$"
  selector-id-pattern: "[a-z\\-]+"
  font-family-name-quotes: always-unless-keyword
  function-url-quotes: always
  selector-attribute-quotes: always
  declaration-block-no-redundant-longhand-properties: true
  shorthand-property-no-redundant-values: true
  comment-whitespace-inside: always
