name: Philomena Build

on: [push, pull_request]

jobs:
  build:
    name: 'Build Elixir app'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: |
            _build
            .cargo
            deps
            priv/native
          key: ${{ runner.os }}-deps-4-${{ hashFiles('mix.lock') }}-${{ hashFiles('native/philomena/**/*.rs', 'native/philomena/**/Cargo.*', 'rust-toolchain.toml') }}

      - run: docker compose pull
      - run: docker compose build
      - name: Run tests
        run: ./scripts/philomena.sh test
      - name: Dump service logs and system state on failure
        if: failure()
        run: |
          docker compose logs --timestamps opensearch postgres valkey
          df -h
          free -h
      # Artifacts from docker bind mount are owned by root, but cache action
      # can only save artifacts running under the default user:
      - name: Change artifact ownership for cache action
        run: sudo chown -R $USER $GITHUB_WORKSPACE

  typos:
    name: 'Check for spelling errors'
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - run: ./scripts/install/typos.sh
      - run: typos

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - run: ./scripts/install/shellcheck.sh
      - run: ./scripts/shellcheck.sh

  cargo:
    name: Rust Linting and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Uses the `rust-toolchain.toml` file
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: cargo fmt
        run: (cd native/philomena && cargo fmt --check)

      - name: cargo clippy
        run: (cd native/philomena && cargo clippy -- -D warnings)

      - name: cargo test
        run: (cd native/philomena && cargo test)

  prettier:
    name: 'Prettier Formatting Check'
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npx prettier --check .

  lint-and-test:
    name: 'JavaScript Linting and Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci --ignore-scripts
        working-directory: ./assets
      - run: npm run lint
        working-directory: ./assets
      - run: npm run test
        working-directory: ./assets
      - run: npm run build
        working-directory: ./assets
